In [3]:
import numpy as np

### 1. Create 10 random numbers between 1 to 100, set seed as 20

In [5]:
np.random.seed(20)
rand_nos = np.random.randint(1,101, size = 10)
rand_nos

array([99, 90, 15, 95, 28, 90,  9, 20, 75, 22])

### 2. Use NumPy to generate a random set of 10 numbers between 0 and 1. 

Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [42]:
np.random.seed(20)

my_array = np.random.rand(10)

print(my_array.size)
print(my_array>0.2)



10
[ True  True  True  True False  True  True  True  True False]


In [41]:
new_array = my_array[my_array>0.2]

print(new_array.size)

print(new_array)


8
[0.5881308  0.89771373 0.89153073 0.81583748 0.69175758 0.37868094
 0.51851095 0.65795147]


### 3. Use NumPy to generate a random set of 10 numbers between 0 and 1. 

Display only the values > 0.2 and less than 0.6

In [40]:
n2_array = my_array[(my_array>0.2) & (my_array<0.6)]
print(n2_array.size)

print(n2_array)

3
[0.5881308  0.37868094 0.51851095]


### 4. Create an array of integers starting from 21 until 31 and name it as array1

--- Create an array of integers starting from 11 until 21 and name it array2

---    Calculate the difference between array1 and array2

In [46]:
array1 = np.arange(21,32)

array2 = np.arange(11,22)

array1 - array2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

### 5. With np.arange(2,11,2), 
--- Change the 2nd and 3rd element to 333
--- For all the values greater than 2, change it to 333 

In [89]:
arr = np.arange(2,11,2)
arr[[1,2]] = 333
arr

array([  2, 333, 333,   8,  10])

In [87]:
### test
arr[0:2] = 333
arr

array([333, 333, 333, 333, 333])

In [90]:
arr[arr>2] = 333
arr

array([  2, 333, 333, 333, 333])

### 6. Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

In [52]:
np.random.randn(5,2)

array([[ 0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447],
       [ 0.32346101, -0.49341088],
       [-0.79201679, -0.84236793],
       [-1.27950266,  0.24571517]])

### 7. Create an array of 30 linearly spaced points between 0 and 100:

In [53]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

### 8. Create a 5x6 matrix with values ranging from 0 to 29 and retrieve the value intersecting at 2nd row and 3rd column

In [55]:
array_matrix = np.arange(30).reshape(5,6)
print(array_matrix)
print(array_matrix[1,2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
8


## Numpy Indexing and Selections

### 9. Using the below given Matrix, generate the output for the below questions.

In [7]:
simple_matrix = np.arange(1,101).reshape(10,10)
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### a) Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [8]:
simple_matrix[8:,0:3]

array([[81, 82, 83],
       [91, 92, 93]])

#### b) Retrieve the last row values from the above matrix

In [12]:
simple_matrix[-1:]

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### c) Retrieve the values from the 3rd column in the above matrix

In [0]:
simple_matrix[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

#### d) Retrieve the values from the 4th row in the above matrix

In [0]:
simple_matrix[3,:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

#### e) Retrieve values from the 2nd & 4th rows in the above matrix

In [0]:
simple_matrix[(1,3),:]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

### Calculate the following values for the given matrix

#### a) Calculate sum of all the values in the matrix

In [0]:
simple_matrix.sum()

5050

#### b) Calculate standard deviation of all the values in the matrix

In [0]:
simple_matrix.std()

28.866070047722118

#### c) Calculate the variance of all the values in the matrix

In [0]:
simple_matrix.var()

833.25

#### d) Calculate the mean of all the values in the matrix

In [0]:
simple_matrix.mean()

50.5

#### e) Retrieve the largest number from the matrix

In [0]:
simple_matrix.max()

100

#### f) Retrieve the smallest number from the matrix

In [0]:
simple_matrix.min()

1

### 10. Create 2 matrix

---  first matrix in shape 3X3, use arange (9), with seed 10

--- second matrix in shape 3X3, use arange(1,10)

In [65]:
np.random.seed(10)
m1 = np.arange(9).reshape(3,3)
print(m1)

m2 = np.arange(1,10)
m2 = m2.reshape(3,3)
print(m2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
Do the below operations
- Addition 
- Subtraction
- Multiplication
- Division
- Dot Product
- Transpose the output of dot product


In [70]:
m1 + m2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [71]:
m1 - m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [72]:
m1 * m2

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [73]:
m1 / m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [67]:
m3dot = m1.dot(m2)
m3dot

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [68]:
m4dot = np.dot(m1,m2)
m4dot

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [69]:
m5tp = np.transpose(m4dot)
print(m5tp)

[[ 18  54  90]
 [ 21  66 111]
 [ 24  78 132]]
