In [1]:
import numpy as np

### 1. Create an array of twenty 0's and replace the 4th element with the number 5.

In [6]:
a = np.zeros(20)

a[3]=5

a

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

### 2. Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [13]:
arr = np.eye(10)

arr[arr == 0] = 21

arr

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

### 3. Create an array of 20 1's and store it as a variable named array_master. Copy the same array into another variable named array_copy

In [7]:
array_master = np.ones(20)

array_copy = array_master.copy()

array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

### 4. Create an array containing 30 1's and broadcast all the one's to the value 100

In [8]:
array = np.ones(30)

array[:] = 100

array

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

### 5. Create an 3X3 empty array, set all the values to 5

In [2]:
np_e = np.empty((3,3))
print(np_e)

[[8.82768938e+025 2.44735062e-284 2.44815100e-284]
 [1.81515960e-284 1.81520064e-284 1.75957391e-284]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [3]:
np_e.fill(5)
print(np_e)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


### 6. Create 3X3 matrix with random integers, set seed as 9

a. Get the maximum value row wise

b. get the minimum value column wise

c. Get the total sum

In [5]:
np.random.seed(9)
np1 = np.random.randint(1,101, size = 9).reshape(3,3)
np1

array([[93, 55, 57],
       [23, 66, 23],
       [53, 60, 41]])

In [6]:
np1.max(axis = 0) # get max value in each row

array([93, 66, 57])

In [10]:
np1.min(axis = 1)# get max value in each column

array([55, 23, 41])

In [11]:
np1.sum()

471

### 7. Create an array of 30 linearly spaced points between 0 and 100. Exclude the endpoint

In [14]:
np.linspace(0,100,30,  endpoint = False)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ,
       33.33333333, 36.66666667, 40.        , 43.33333333, 46.66666667,
       50.        , 53.33333333, 56.66666667, 60.        , 63.33333333,
       66.66666667, 70.        , 73.33333333, 76.66666667, 80.        ,
       83.33333333, 86.66666667, 90.        , 93.33333333, 96.66666667])

### 8. Create an array of all even integers from 2 to 10 and name it a1, Create an array of all even integers from 22 to 30 and name it a2

####  a) Use the 2 arrays as rows and create a matrix
[ Hint - Use stack function from numpy ]

In [47]:
a1 = np.arange(2,11,2)

a2 = np.arange(22,31,2)

np.stack((a1,a2))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

####   b) Use the 2 arrays as columns and create a matrix [ Hint - Use column_stack function from numpy ]

In [49]:
np.column_stack((a1,a2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

### 9. Create 2 arrays and append the data horizontally

np1 = np.arange(5*6).reshape(5,6)

np2 = np.arange(5*5).reshape(5,5)


In [24]:
np1 = np.arange(5*6).reshape(5,6)

np1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [25]:
np2 = np.arange(5*5).reshape(5,5)

np2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
np.hstack((np1,np2))

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10, 11,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 10, 11, 12, 13, 14],
       [18, 19, 20, 21, 22, 23, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29, 20, 21, 22, 23, 24]])

### 10. Create 2 arrays and append the data vertically

np1 = np.arange(3*5).reshape(3,5)

np2 = np.arange(4*5).reshape(4,5)



In [26]:
np1 = np.arange(3*5).reshape(3,5)

np1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
np2 = np.arange(4*5).reshape(4,5)

np2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
np.vstack((np1,np2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 11. Create an array and split into 2 (column wise)

np1 = np.arange(3*4).reshape(3,4)


In [37]:
np1 = np.arange(3*4).reshape(3,4)
np1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
np.hsplit(np1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

### 12. Create an array and split into 2 (row wise)

np1 = np.arange(6*4).reshape(6,4)


In [46]:
np1 = np.arange(6*4).reshape(6,4)
np1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
np.vsplit(np1,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

### 13. Create an array and split into 3 (columns wise)

np1 = np.arange(6*4).reshape(6,4)

In [50]:
np1 = np.arange(6*4).reshape(6,4)
np1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
np.hsplit(np1,[1,3,5])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]]),
 array([], shape=(6, 0), dtype=int32)]

### 14. Create an array using np1 = np.arange(6*4).reshape(6,4)

-- Split like below 

-- first three columns, last column

In [66]:
np1 = np.arange(6*4).reshape(6,4)
np1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
np.hsplit(np1,[3,])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14],
        [16, 17, 18],
        [20, 21, 22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

### 15. Create an array using np1 = np.arange(6*4).reshape(6,4)

-- Split like below 

-- first three rows, the 3rd and 4th row, last 4 rows

In [63]:
np1 = np.arange(6*4).reshape(6,4)
np1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
np.vsplit(np1,[3,5])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]